version: '3'
services:
  app:
    image: bank-account-rest-api
    container_name: api_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1620:1620"
    volumes:
      - ./log:/var/lib/bank-account-rest-api/log
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bank
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:14.7-alpine
    container_name: postgres_container
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5433:5433"
    expose:
      - "6432"
    restart: unless-stopped
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - bankdb-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.8
    environment:
      PGADMIN_DEFAULT_EMAIL: "oleg1n@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  bankdb-data:
  pgadmin-data:
